### ISSUE TITLE
Fix settings in web interface

### ISSUE THREAD

**Issue by CircuitSetup** [CircuitSetup/Time-Circuits-Display#6]
Currently the web interface has fields for:
- Beep Sound
- NTP Time Server
- Brightness per display

Currently these are placeholders and do not affect anything. They need to be tied into the actual variables that control these parameters. Web interface variables are defined in tc_wifi.cpp

**Comment by CircuitSetup** [comment]
Also need to add a fields for 
- Time zone offset
- DST

**Comment by CircuitSetup** [comment]
This is fixed with eb9f815

**Comment by Ricky3Nut** [comment]
Thanks John. Do I have to update the module or something to get the fix to take effect? I am still not able to set the time on the web interface or adjust for my time zone.

**Comment by CircuitSetup** [comment]
> Thanks John. Do I have to update the module or something to get the fix to take effect? I am still not able to set the time on the web interface or adjust for my time zone.

Yes. There is an option to update software from the web interface. I have to post the compiled .bin file though. Stay tuned.
